name: Lightning

on:
  pull_request:
    paths:
      - ".github/workflows/lightning.yml"
      - "**.zig"
  push:
    paths:
      - ".github/workflows/lightning.yml"
      - "**.zig"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: davidgm94/setup-qemu@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Zig environment variables
        run: zig env
      - name: Build test executables
        run: zig build all_tests -Dci --verbose
      - name: Test with QEMU
        run: zig build test_all -Dci --verbose

