name: Lightning

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: davidgm94/setup-qemu@main
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: sh ci/build_and_test.sh

  build_and_test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: davidgm94/setup-qemu@main
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: sh ci/build_and_test.sh

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig env
      - run: zig build all
      - run: zig build all_tests
