name: Lightning
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - run: zig version
    - run: zig env

    - name: Build
    - run: zig build
