name: Lightning

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: davidgm94/setup-qemu@main
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig env
      - run: zig build test_all -Dci --verbose

